#!/bin/sh
### BEGIN INIT INFO
# Provides: kiwix-server
# Should-Start: kiwix-server
# Required-Start: $all
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start kiwix-server at boot time
### END INIT INFO
#
# Change the value of "user" to your linux user name
user=root

# Change the value of "kiwix_dir" to your path of kiwix installation
kiwix_dir=KIWIX_DIR
script_path=${kiwix_dir}/bin

# Set the port, default is 8080. Change it if you need different.
kiwix_port=KIWIX_PORT

case "$1" in
        start)
                nohup sudo -u ${user} ${script_path}/kiwix-serve --port=${kiwix_port} --library ${kiwix_dir}/library.xml --daemon
        ;;
        restart)
                sudo -u ${user} killall kiwix-serve
                nohup sudo -u ${user} ${script_path}/kiwix-serve --port=${kiwix_port} --library ${kiwix_dir}/library.xml --daemon
        ;;
        stop)
                sudo -u ${user} killall kiwix-serve
        ;;
        *)
                echo "Usage: /etc/init.d/kiwix-server {start|stop|restart}"
                exit 1
        ;;
esac